### ISSUE TITLE
0.8.0 build failed

### ISSUE THREAD

**Issue by daniel88ferreira** [conda-forge/flask-testing-feedstock#7]
0.8.0 build failed
https://github.com/conda-forge/flask-testing-feedstock/commit/c999f3de300563474818030eea35425f8a978ff0
@marcelotrevisani can you help?

**Comment by daniel88ferreira** [comment]
@marcelotrevisani can you help?

**Comment by daniel88ferreira** [comment]
Still failing https://github.com/conda-forge/flask-testing-feedstock/commit/c3a5643aea1844101d9d98fde661ae633289ef9e
Can I do something to help?

**Comment by marcelotrevisani** [comment]
solved with the rerender, thanks!
